### ISSUE TITLE
module definition for clk_wiz_1 is missing.

### ISSUE THREAD

**Issue by akhileshian** [nchronas/GSoC-2017#1]
I am trying to find the module definition for clk_wiz_1, for lowrisc SoC, in the minion subsystem. I came across your article, stating that it is not present in the git repository. Any ideas where I would be able to find it? If not, is there any documentation as to what that module contains, so that I can recreate it?

Regards,
Akhilesh Iyer.

**Comment by nchronas** [comment]
Hello,

I think that the module is not present in the repo for licensing reasons. Since I didn't use the SD I always changed the definition to "assign msoc_clock = sd_clk_o". I think there was instructions somewhere in the documents but I cannot find it right now.

I think that the best approach would be to send an email to the lowrisk dev list or open an issue the the [minion subsystem](https://github.com/lowRISC/minion_subsystem/).

Hoped that you liked my article :)
